// Generated by jextract

package org.skor.jhighs.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     void *cbdata;
 *     int log_type;
 *     double running_time;
 *     HighsInt simplex_iteration_count;
 *     HighsInt ipm_iteration_count;
 *     HighsInt pdlp_iteration_count;
 *     double objective_function_value;
 *     int64_t mip_node_count;
 *     int64_t mip_total_lp_iterations;
 *     double mip_primal_bound;
 *     double mip_dual_bound;
 *     double mip_gap;
 *     double *mip_solution;
 *     HighsInt mip_solution_size;
 *     HighsInt cutpool_num_col;
 *     HighsInt cutpool_num_cut;
 *     HighsInt cutpool_num_nz;
 *     HighsInt *cutpool_start;
 *     HighsInt *cutpool_index;
 *     double *cutpool_value;
 *     double *cutpool_lower;
 *     double *cutpool_upper;
 *     HighsInt external_solution_query_origin;
 * }
 * }
 */
public class HighsCallbackDataOut {

    HighsCallbackDataOut() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        highs_c_api_h.C_POINTER.withName("cbdata"),
        highs_c_api_h.C_INT.withName("log_type"),
        MemoryLayout.paddingLayout(4),
        highs_c_api_h.C_DOUBLE.withName("running_time"),
        highs_c_api_h.C_LONG.withName("simplex_iteration_count"),
        highs_c_api_h.C_LONG.withName("ipm_iteration_count"),
        highs_c_api_h.C_LONG.withName("pdlp_iteration_count"),
        highs_c_api_h.C_DOUBLE.withName("objective_function_value"),
        highs_c_api_h.C_LONG.withName("mip_node_count"),
        highs_c_api_h.C_LONG.withName("mip_total_lp_iterations"),
        highs_c_api_h.C_DOUBLE.withName("mip_primal_bound"),
        highs_c_api_h.C_DOUBLE.withName("mip_dual_bound"),
        highs_c_api_h.C_DOUBLE.withName("mip_gap"),
        highs_c_api_h.C_POINTER.withName("mip_solution"),
        highs_c_api_h.C_LONG.withName("mip_solution_size"),
        highs_c_api_h.C_LONG.withName("cutpool_num_col"),
        highs_c_api_h.C_LONG.withName("cutpool_num_cut"),
        highs_c_api_h.C_LONG.withName("cutpool_num_nz"),
        highs_c_api_h.C_POINTER.withName("cutpool_start"),
        highs_c_api_h.C_POINTER.withName("cutpool_index"),
        highs_c_api_h.C_POINTER.withName("cutpool_value"),
        highs_c_api_h.C_POINTER.withName("cutpool_lower"),
        highs_c_api_h.C_POINTER.withName("cutpool_upper"),
        highs_c_api_h.C_LONG.withName("external_solution_query_origin")
    ).withName("$anon$24:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout cbdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cbdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static final AddressLayout cbdata$layout() {
        return cbdata$LAYOUT;
    }

    private static final long cbdata$OFFSET = $LAYOUT.byteOffset(groupElement("cbdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static final long cbdata$offset() {
        return cbdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static MemorySegment cbdata(MemorySegment struct) {
        return struct.get(cbdata$LAYOUT, cbdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static void cbdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cbdata$LAYOUT, cbdata$OFFSET, fieldValue);
    }

    private static final OfInt log_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("log_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int log_type
     * }
     */
    public static final OfInt log_type$layout() {
        return log_type$LAYOUT;
    }

    private static final long log_type$OFFSET = $LAYOUT.byteOffset(groupElement("log_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int log_type
     * }
     */
    public static final long log_type$offset() {
        return log_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int log_type
     * }
     */
    public static int log_type(MemorySegment struct) {
        return struct.get(log_type$LAYOUT, log_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int log_type
     * }
     */
    public static void log_type(MemorySegment struct, int fieldValue) {
        struct.set(log_type$LAYOUT, log_type$OFFSET, fieldValue);
    }

    private static final OfDouble running_time$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("running_time"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double running_time
     * }
     */
    public static final OfDouble running_time$layout() {
        return running_time$LAYOUT;
    }

    private static final long running_time$OFFSET = $LAYOUT.byteOffset(groupElement("running_time"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double running_time
     * }
     */
    public static final long running_time$offset() {
        return running_time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double running_time
     * }
     */
    public static double running_time(MemorySegment struct) {
        return struct.get(running_time$LAYOUT, running_time$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double running_time
     * }
     */
    public static void running_time(MemorySegment struct, double fieldValue) {
        struct.set(running_time$LAYOUT, running_time$OFFSET, fieldValue);
    }

    private static final OfLong simplex_iteration_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("simplex_iteration_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt simplex_iteration_count
     * }
     */
    public static final OfLong simplex_iteration_count$layout() {
        return simplex_iteration_count$LAYOUT;
    }

    private static final long simplex_iteration_count$OFFSET = $LAYOUT.byteOffset(groupElement("simplex_iteration_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt simplex_iteration_count
     * }
     */
    public static final long simplex_iteration_count$offset() {
        return simplex_iteration_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt simplex_iteration_count
     * }
     */
    public static long simplex_iteration_count(MemorySegment struct) {
        return struct.get(simplex_iteration_count$LAYOUT, simplex_iteration_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt simplex_iteration_count
     * }
     */
    public static void simplex_iteration_count(MemorySegment struct, long fieldValue) {
        struct.set(simplex_iteration_count$LAYOUT, simplex_iteration_count$OFFSET, fieldValue);
    }

    private static final OfLong ipm_iteration_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ipm_iteration_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt ipm_iteration_count
     * }
     */
    public static final OfLong ipm_iteration_count$layout() {
        return ipm_iteration_count$LAYOUT;
    }

    private static final long ipm_iteration_count$OFFSET = $LAYOUT.byteOffset(groupElement("ipm_iteration_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt ipm_iteration_count
     * }
     */
    public static final long ipm_iteration_count$offset() {
        return ipm_iteration_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt ipm_iteration_count
     * }
     */
    public static long ipm_iteration_count(MemorySegment struct) {
        return struct.get(ipm_iteration_count$LAYOUT, ipm_iteration_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt ipm_iteration_count
     * }
     */
    public static void ipm_iteration_count(MemorySegment struct, long fieldValue) {
        struct.set(ipm_iteration_count$LAYOUT, ipm_iteration_count$OFFSET, fieldValue);
    }

    private static final OfLong pdlp_iteration_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("pdlp_iteration_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt pdlp_iteration_count
     * }
     */
    public static final OfLong pdlp_iteration_count$layout() {
        return pdlp_iteration_count$LAYOUT;
    }

    private static final long pdlp_iteration_count$OFFSET = $LAYOUT.byteOffset(groupElement("pdlp_iteration_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt pdlp_iteration_count
     * }
     */
    public static final long pdlp_iteration_count$offset() {
        return pdlp_iteration_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt pdlp_iteration_count
     * }
     */
    public static long pdlp_iteration_count(MemorySegment struct) {
        return struct.get(pdlp_iteration_count$LAYOUT, pdlp_iteration_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt pdlp_iteration_count
     * }
     */
    public static void pdlp_iteration_count(MemorySegment struct, long fieldValue) {
        struct.set(pdlp_iteration_count$LAYOUT, pdlp_iteration_count$OFFSET, fieldValue);
    }

    private static final OfDouble objective_function_value$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("objective_function_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double objective_function_value
     * }
     */
    public static final OfDouble objective_function_value$layout() {
        return objective_function_value$LAYOUT;
    }

    private static final long objective_function_value$OFFSET = $LAYOUT.byteOffset(groupElement("objective_function_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double objective_function_value
     * }
     */
    public static final long objective_function_value$offset() {
        return objective_function_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double objective_function_value
     * }
     */
    public static double objective_function_value(MemorySegment struct) {
        return struct.get(objective_function_value$LAYOUT, objective_function_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double objective_function_value
     * }
     */
    public static void objective_function_value(MemorySegment struct, double fieldValue) {
        struct.set(objective_function_value$LAYOUT, objective_function_value$OFFSET, fieldValue);
    }

    private static final OfLong mip_node_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("mip_node_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t mip_node_count
     * }
     */
    public static final OfLong mip_node_count$layout() {
        return mip_node_count$LAYOUT;
    }

    private static final long mip_node_count$OFFSET = $LAYOUT.byteOffset(groupElement("mip_node_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t mip_node_count
     * }
     */
    public static final long mip_node_count$offset() {
        return mip_node_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t mip_node_count
     * }
     */
    public static long mip_node_count(MemorySegment struct) {
        return struct.get(mip_node_count$LAYOUT, mip_node_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t mip_node_count
     * }
     */
    public static void mip_node_count(MemorySegment struct, long fieldValue) {
        struct.set(mip_node_count$LAYOUT, mip_node_count$OFFSET, fieldValue);
    }

    private static final OfLong mip_total_lp_iterations$LAYOUT = (OfLong)$LAYOUT.select(groupElement("mip_total_lp_iterations"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t mip_total_lp_iterations
     * }
     */
    public static final OfLong mip_total_lp_iterations$layout() {
        return mip_total_lp_iterations$LAYOUT;
    }

    private static final long mip_total_lp_iterations$OFFSET = $LAYOUT.byteOffset(groupElement("mip_total_lp_iterations"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t mip_total_lp_iterations
     * }
     */
    public static final long mip_total_lp_iterations$offset() {
        return mip_total_lp_iterations$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t mip_total_lp_iterations
     * }
     */
    public static long mip_total_lp_iterations(MemorySegment struct) {
        return struct.get(mip_total_lp_iterations$LAYOUT, mip_total_lp_iterations$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t mip_total_lp_iterations
     * }
     */
    public static void mip_total_lp_iterations(MemorySegment struct, long fieldValue) {
        struct.set(mip_total_lp_iterations$LAYOUT, mip_total_lp_iterations$OFFSET, fieldValue);
    }

    private static final OfDouble mip_primal_bound$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mip_primal_bound"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mip_primal_bound
     * }
     */
    public static final OfDouble mip_primal_bound$layout() {
        return mip_primal_bound$LAYOUT;
    }

    private static final long mip_primal_bound$OFFSET = $LAYOUT.byteOffset(groupElement("mip_primal_bound"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mip_primal_bound
     * }
     */
    public static final long mip_primal_bound$offset() {
        return mip_primal_bound$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mip_primal_bound
     * }
     */
    public static double mip_primal_bound(MemorySegment struct) {
        return struct.get(mip_primal_bound$LAYOUT, mip_primal_bound$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mip_primal_bound
     * }
     */
    public static void mip_primal_bound(MemorySegment struct, double fieldValue) {
        struct.set(mip_primal_bound$LAYOUT, mip_primal_bound$OFFSET, fieldValue);
    }

    private static final OfDouble mip_dual_bound$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mip_dual_bound"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mip_dual_bound
     * }
     */
    public static final OfDouble mip_dual_bound$layout() {
        return mip_dual_bound$LAYOUT;
    }

    private static final long mip_dual_bound$OFFSET = $LAYOUT.byteOffset(groupElement("mip_dual_bound"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mip_dual_bound
     * }
     */
    public static final long mip_dual_bound$offset() {
        return mip_dual_bound$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mip_dual_bound
     * }
     */
    public static double mip_dual_bound(MemorySegment struct) {
        return struct.get(mip_dual_bound$LAYOUT, mip_dual_bound$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mip_dual_bound
     * }
     */
    public static void mip_dual_bound(MemorySegment struct, double fieldValue) {
        struct.set(mip_dual_bound$LAYOUT, mip_dual_bound$OFFSET, fieldValue);
    }

    private static final OfDouble mip_gap$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mip_gap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mip_gap
     * }
     */
    public static final OfDouble mip_gap$layout() {
        return mip_gap$LAYOUT;
    }

    private static final long mip_gap$OFFSET = $LAYOUT.byteOffset(groupElement("mip_gap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mip_gap
     * }
     */
    public static final long mip_gap$offset() {
        return mip_gap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mip_gap
     * }
     */
    public static double mip_gap(MemorySegment struct) {
        return struct.get(mip_gap$LAYOUT, mip_gap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mip_gap
     * }
     */
    public static void mip_gap(MemorySegment struct, double fieldValue) {
        struct.set(mip_gap$LAYOUT, mip_gap$OFFSET, fieldValue);
    }

    private static final AddressLayout mip_solution$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mip_solution"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *mip_solution
     * }
     */
    public static final AddressLayout mip_solution$layout() {
        return mip_solution$LAYOUT;
    }

    private static final long mip_solution$OFFSET = $LAYOUT.byteOffset(groupElement("mip_solution"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *mip_solution
     * }
     */
    public static final long mip_solution$offset() {
        return mip_solution$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *mip_solution
     * }
     */
    public static MemorySegment mip_solution(MemorySegment struct) {
        return struct.get(mip_solution$LAYOUT, mip_solution$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *mip_solution
     * }
     */
    public static void mip_solution(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mip_solution$LAYOUT, mip_solution$OFFSET, fieldValue);
    }

    private static final OfLong mip_solution_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("mip_solution_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt mip_solution_size
     * }
     */
    public static final OfLong mip_solution_size$layout() {
        return mip_solution_size$LAYOUT;
    }

    private static final long mip_solution_size$OFFSET = $LAYOUT.byteOffset(groupElement("mip_solution_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt mip_solution_size
     * }
     */
    public static final long mip_solution_size$offset() {
        return mip_solution_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt mip_solution_size
     * }
     */
    public static long mip_solution_size(MemorySegment struct) {
        return struct.get(mip_solution_size$LAYOUT, mip_solution_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt mip_solution_size
     * }
     */
    public static void mip_solution_size(MemorySegment struct, long fieldValue) {
        struct.set(mip_solution_size$LAYOUT, mip_solution_size$OFFSET, fieldValue);
    }

    private static final OfLong cutpool_num_col$LAYOUT = (OfLong)$LAYOUT.select(groupElement("cutpool_num_col"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_col
     * }
     */
    public static final OfLong cutpool_num_col$layout() {
        return cutpool_num_col$LAYOUT;
    }

    private static final long cutpool_num_col$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_num_col"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_col
     * }
     */
    public static final long cutpool_num_col$offset() {
        return cutpool_num_col$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_col
     * }
     */
    public static long cutpool_num_col(MemorySegment struct) {
        return struct.get(cutpool_num_col$LAYOUT, cutpool_num_col$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_col
     * }
     */
    public static void cutpool_num_col(MemorySegment struct, long fieldValue) {
        struct.set(cutpool_num_col$LAYOUT, cutpool_num_col$OFFSET, fieldValue);
    }

    private static final OfLong cutpool_num_cut$LAYOUT = (OfLong)$LAYOUT.select(groupElement("cutpool_num_cut"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_cut
     * }
     */
    public static final OfLong cutpool_num_cut$layout() {
        return cutpool_num_cut$LAYOUT;
    }

    private static final long cutpool_num_cut$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_num_cut"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_cut
     * }
     */
    public static final long cutpool_num_cut$offset() {
        return cutpool_num_cut$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_cut
     * }
     */
    public static long cutpool_num_cut(MemorySegment struct) {
        return struct.get(cutpool_num_cut$LAYOUT, cutpool_num_cut$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_cut
     * }
     */
    public static void cutpool_num_cut(MemorySegment struct, long fieldValue) {
        struct.set(cutpool_num_cut$LAYOUT, cutpool_num_cut$OFFSET, fieldValue);
    }

    private static final OfLong cutpool_num_nz$LAYOUT = (OfLong)$LAYOUT.select(groupElement("cutpool_num_nz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_nz
     * }
     */
    public static final OfLong cutpool_num_nz$layout() {
        return cutpool_num_nz$LAYOUT;
    }

    private static final long cutpool_num_nz$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_num_nz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_nz
     * }
     */
    public static final long cutpool_num_nz$offset() {
        return cutpool_num_nz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_nz
     * }
     */
    public static long cutpool_num_nz(MemorySegment struct) {
        return struct.get(cutpool_num_nz$LAYOUT, cutpool_num_nz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt cutpool_num_nz
     * }
     */
    public static void cutpool_num_nz(MemorySegment struct, long fieldValue) {
        struct.set(cutpool_num_nz$LAYOUT, cutpool_num_nz$OFFSET, fieldValue);
    }

    private static final AddressLayout cutpool_start$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cutpool_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_start
     * }
     */
    public static final AddressLayout cutpool_start$layout() {
        return cutpool_start$LAYOUT;
    }

    private static final long cutpool_start$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_start
     * }
     */
    public static final long cutpool_start$offset() {
        return cutpool_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_start
     * }
     */
    public static MemorySegment cutpool_start(MemorySegment struct) {
        return struct.get(cutpool_start$LAYOUT, cutpool_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_start
     * }
     */
    public static void cutpool_start(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cutpool_start$LAYOUT, cutpool_start$OFFSET, fieldValue);
    }

    private static final AddressLayout cutpool_index$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cutpool_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_index
     * }
     */
    public static final AddressLayout cutpool_index$layout() {
        return cutpool_index$LAYOUT;
    }

    private static final long cutpool_index$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_index
     * }
     */
    public static final long cutpool_index$offset() {
        return cutpool_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_index
     * }
     */
    public static MemorySegment cutpool_index(MemorySegment struct) {
        return struct.get(cutpool_index$LAYOUT, cutpool_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt *cutpool_index
     * }
     */
    public static void cutpool_index(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cutpool_index$LAYOUT, cutpool_index$OFFSET, fieldValue);
    }

    private static final AddressLayout cutpool_value$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cutpool_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *cutpool_value
     * }
     */
    public static final AddressLayout cutpool_value$layout() {
        return cutpool_value$LAYOUT;
    }

    private static final long cutpool_value$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *cutpool_value
     * }
     */
    public static final long cutpool_value$offset() {
        return cutpool_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *cutpool_value
     * }
     */
    public static MemorySegment cutpool_value(MemorySegment struct) {
        return struct.get(cutpool_value$LAYOUT, cutpool_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *cutpool_value
     * }
     */
    public static void cutpool_value(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cutpool_value$LAYOUT, cutpool_value$OFFSET, fieldValue);
    }

    private static final AddressLayout cutpool_lower$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cutpool_lower"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *cutpool_lower
     * }
     */
    public static final AddressLayout cutpool_lower$layout() {
        return cutpool_lower$LAYOUT;
    }

    private static final long cutpool_lower$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_lower"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *cutpool_lower
     * }
     */
    public static final long cutpool_lower$offset() {
        return cutpool_lower$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *cutpool_lower
     * }
     */
    public static MemorySegment cutpool_lower(MemorySegment struct) {
        return struct.get(cutpool_lower$LAYOUT, cutpool_lower$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *cutpool_lower
     * }
     */
    public static void cutpool_lower(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cutpool_lower$LAYOUT, cutpool_lower$OFFSET, fieldValue);
    }

    private static final AddressLayout cutpool_upper$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cutpool_upper"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *cutpool_upper
     * }
     */
    public static final AddressLayout cutpool_upper$layout() {
        return cutpool_upper$LAYOUT;
    }

    private static final long cutpool_upper$OFFSET = $LAYOUT.byteOffset(groupElement("cutpool_upper"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *cutpool_upper
     * }
     */
    public static final long cutpool_upper$offset() {
        return cutpool_upper$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *cutpool_upper
     * }
     */
    public static MemorySegment cutpool_upper(MemorySegment struct) {
        return struct.get(cutpool_upper$LAYOUT, cutpool_upper$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *cutpool_upper
     * }
     */
    public static void cutpool_upper(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cutpool_upper$LAYOUT, cutpool_upper$OFFSET, fieldValue);
    }

    private static final OfLong external_solution_query_origin$LAYOUT = (OfLong)$LAYOUT.select(groupElement("external_solution_query_origin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt external_solution_query_origin
     * }
     */
    public static final OfLong external_solution_query_origin$layout() {
        return external_solution_query_origin$LAYOUT;
    }

    private static final long external_solution_query_origin$OFFSET = $LAYOUT.byteOffset(groupElement("external_solution_query_origin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt external_solution_query_origin
     * }
     */
    public static final long external_solution_query_origin$offset() {
        return external_solution_query_origin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt external_solution_query_origin
     * }
     */
    public static long external_solution_query_origin(MemorySegment struct) {
        return struct.get(external_solution_query_origin$LAYOUT, external_solution_query_origin$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt external_solution_query_origin
     * }
     */
    public static void external_solution_query_origin(MemorySegment struct, long fieldValue) {
        struct.set(external_solution_query_origin$LAYOUT, external_solution_query_origin$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

