// Generated by jextract

package org.skor.jhighs.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int user_interrupt;
 *     double *user_solution;
 *     void *cbdata;
 *     int user_has_solution;
 *     HighsInt user_solution_size;
 * }
 * }
 */
public class HighsCallbackDataIn {

    HighsCallbackDataIn() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        highs_c_api_h.C_INT.withName("user_interrupt"),
        MemoryLayout.paddingLayout(4),
        highs_c_api_h.C_POINTER.withName("user_solution"),
        highs_c_api_h.C_POINTER.withName("cbdata"),
        highs_c_api_h.C_INT.withName("user_has_solution"),
        MemoryLayout.paddingLayout(4),
        highs_c_api_h.C_LONG.withName("user_solution_size")
    ).withName("$anon$53:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt user_interrupt$LAYOUT = (OfInt)$LAYOUT.select(groupElement("user_interrupt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int user_interrupt
     * }
     */
    public static final OfInt user_interrupt$layout() {
        return user_interrupt$LAYOUT;
    }

    private static final long user_interrupt$OFFSET = $LAYOUT.byteOffset(groupElement("user_interrupt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int user_interrupt
     * }
     */
    public static final long user_interrupt$offset() {
        return user_interrupt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int user_interrupt
     * }
     */
    public static int user_interrupt(MemorySegment struct) {
        return struct.get(user_interrupt$LAYOUT, user_interrupt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int user_interrupt
     * }
     */
    public static void user_interrupt(MemorySegment struct, int fieldValue) {
        struct.set(user_interrupt$LAYOUT, user_interrupt$OFFSET, fieldValue);
    }

    private static final AddressLayout user_solution$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_solution"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *user_solution
     * }
     */
    public static final AddressLayout user_solution$layout() {
        return user_solution$LAYOUT;
    }

    private static final long user_solution$OFFSET = $LAYOUT.byteOffset(groupElement("user_solution"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *user_solution
     * }
     */
    public static final long user_solution$offset() {
        return user_solution$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *user_solution
     * }
     */
    public static MemorySegment user_solution(MemorySegment struct) {
        return struct.get(user_solution$LAYOUT, user_solution$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *user_solution
     * }
     */
    public static void user_solution(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_solution$LAYOUT, user_solution$OFFSET, fieldValue);
    }

    private static final AddressLayout cbdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cbdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static final AddressLayout cbdata$layout() {
        return cbdata$LAYOUT;
    }

    private static final long cbdata$OFFSET = $LAYOUT.byteOffset(groupElement("cbdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static final long cbdata$offset() {
        return cbdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static MemorySegment cbdata(MemorySegment struct) {
        return struct.get(cbdata$LAYOUT, cbdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *cbdata
     * }
     */
    public static void cbdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cbdata$LAYOUT, cbdata$OFFSET, fieldValue);
    }

    private static final OfInt user_has_solution$LAYOUT = (OfInt)$LAYOUT.select(groupElement("user_has_solution"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int user_has_solution
     * }
     */
    public static final OfInt user_has_solution$layout() {
        return user_has_solution$LAYOUT;
    }

    private static final long user_has_solution$OFFSET = $LAYOUT.byteOffset(groupElement("user_has_solution"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int user_has_solution
     * }
     */
    public static final long user_has_solution$offset() {
        return user_has_solution$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int user_has_solution
     * }
     */
    public static int user_has_solution(MemorySegment struct) {
        return struct.get(user_has_solution$LAYOUT, user_has_solution$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int user_has_solution
     * }
     */
    public static void user_has_solution(MemorySegment struct, int fieldValue) {
        struct.set(user_has_solution$LAYOUT, user_has_solution$OFFSET, fieldValue);
    }

    private static final OfLong user_solution_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("user_solution_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HighsInt user_solution_size
     * }
     */
    public static final OfLong user_solution_size$layout() {
        return user_solution_size$LAYOUT;
    }

    private static final long user_solution_size$OFFSET = $LAYOUT.byteOffset(groupElement("user_solution_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HighsInt user_solution_size
     * }
     */
    public static final long user_solution_size$offset() {
        return user_solution_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HighsInt user_solution_size
     * }
     */
    public static long user_solution_size(MemorySegment struct) {
        return struct.get(user_solution_size$LAYOUT, user_solution_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HighsInt user_solution_size
     * }
     */
    public static void user_solution_size(MemorySegment struct, long fieldValue) {
        struct.set(user_solution_size$LAYOUT, user_solution_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

